@startuml
class EntidadGeográfica{
Código: 1 Texto
Nombre: 1 Texto
}

class Linea{}
class Area{}
class Punto{
X: 1 Numero
Y:1 Numero
Z: 1 Numero
}

EntidadGeográfica <|-- Linea
EntidadGeográfica <|-- Area
EntidadGeográfica <|-- Punto

Linea "0..*" o--"2..*" Punto
Area "0..*" o-- "3..*" Punto
@enduml