@startuml

class pt1{
  x:-10
  y:10
}
pol1 o-- pt1  :posee >

class pt2{
  x:10
  y:10
}
pol1 o-- pt2  :posee >
class pol1{

}

class pt3{
  x:-10
  y:-10
}

pol1 o-- pt3  :posee >
class pt4{
  x:10
  y:-10
}


pol1 o-- pt4  :posee >


@enduml