@startuml


Class Restauracion{
  Fecha: 1 Tiempo
  Descripcion: 1 Texto
  Tecnica: 1..* enum TecnicaRestauracion
}

Restauracion "0..*"--"1..*" Objeto : Se ha realizado sobre >

Class Objeto{
  Codigo: 1..* Numero
  Nombre: 1 Texto
  Autor: 1 Texto
  Fecha de creacion: 1 Tiempo
  Descripcion: 0..1 Texto
  Origen: 1 enum Lugar
  Estado: 1 enum Estado
  Tematica: 1..* enum Tematica
} 
Objeto "1..*"--"0.1" Coleccion : Pertenece a >
Objeto "0..*"--"1"Ubicacion : Se ubuca en >

Class Coleccion{
  Nombre: 1 Texto
  Descripcion: 1 Texto
} 

Class ColeccionTemporal {
  Fecha de inicio: 1 Tiempo
  Fecha de fin: 1 Tiempo
}

Coleccion<|-- ColeccionTemporal

Class Ubicacion{
  Codigo: 1 Texto
}

Ubicacion<|-- Sala
Ubicacion <|-- Almacen

Class Sala{
  Nombre: 1 Texto
  Esta abierta al publico: 1 Booleano
}

Planta"1*" o-- "0..*" Sala

Class Almacen{
  Nombre: 1 Texto
}

Class Planta{
  Numero: 1 Numero
}

Edificio"1" o-- "1..*" Planta

Class Edificio{
  Nombre: 1 Texto
  Direccion: 1 Texto
}
@enduml